xcodeproj 'TDTHotChocolateTests'
workspace '../TDTHotChocolate'

def import_pods
  pod 'TDTHotChocolate', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOSTests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OSXTests'
  import_pods
end
