source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:talk-to/private-cocoapod-specs.git'

use_frameworks!

abstract_target 'CommonPods' do
    pod 'TDTChocolate', :path => '../'

    target :iOSTests do
        platform :ios, '8.0'
    end
    target :OSXTests do
        platform :osx, '10.9'
    end
end
